import type { Course, Job, featuredCourse } from "./types";

export const featuredCourses: featuredCourse[] = [
  {
    id: "1",
    title: "DaVinci Resolve Mastery: The Ultimate Video Editing Bootcamp",
    description:
      " Learn Video Editing, Color Correction, Color Grading, Visual Effects in DaVinci Resolve latest versions",
    instructor: "Louay Al-Khatib",
    thumbnail: "/image/davinci.jpg",
    rating: 4.8,
    reviewCount: 45892,
    students: "150K+",
    duration: "63h",
    level: "Intermediate",
    price: 3000,
    categories: [
      "Video Editing",
      "Color Correction",
      "Color Grading",
      "Visual Effects",
    ],
  },
  {
    id: "2",
    title: "Machine Learning A-Z: Hands-On Python & R",
    description:
      "Learn to create Machine Learning Algorithms in Python and R from two Data Science experts",
    instructor: "Kirill Eremenko",
    thumbnail: "/image/machine-learning.jpg",
    rating: 4.6,
    reviewCount: 32145,
    students: "120K+",
    duration: "44h",
    level: "Intermediate",
    price: 3000,
    categories: ["Data Science", "Machine Learning", "Python"],
  },
  {
    id: "3",
    title: "Complete Blender Megacourse: Beginner to Expert",
    description:
      "Learn how to work with Blender like a pro with this 3-in-1 course! Now covering the latest updates in Blender 4.0!",
    instructor: "Rob Percival",
    thumbnail: "/image/blender.jpg",
    rating: 4.5,
    reviewCount: 23456,
    students: "90K+",
    duration: "52h",
    level: "Beginner",
    price: 3000,
    categories: ["3D Modeling", "3D Animation", "3D Rendering"],
  },
  {
    id: "4",
    title: "The Complete Forex Trading Course: More than 5 Courses in 1",
    description:
      "Learn everything you need to know about forex trading, including investing, mining and much more!",
    instructor: "Stephen Grider",
    thumbnail: "/image/forex.jpg",
    rating: 4.7,
    reviewCount: 12345,
    students: "70K+",
    duration: "21h",
    level: "Advanced",
    price: 3000,
    categories: ["Forex Trading", "Forex Trading", "Forex Trading"],
  },
];

export const featuredJobs: Job[] = [
  {
    id: "1",
    title: "Graphic Design",
    company: "TechCorp",
    companyLogo: "/image/logo1.jpg?height=100&width=100",
    location: "Remote",
    type: "Full-time",
    salary: "90K - 120K",
    description:
      "We're looking for a Senior Frontend Developer with strong React experience to join our team. You'll be responsible for building user interfaces for our enterprise applications.",
    skills: ["React", "TypeScript", "CSS", "Redux"],
    postedAt: "2023-06-15",
  },
  {
    id: "2",
    title: "Data Scientist",
    company: "AnalyticsPro",
    companyLogo: "/image/logo2.jpg?height=100&width=100",
    location: "New York, NY",
    type: "Full-time",
    salary: "100K - 130K",
    description:
      "Join our data science team to develop machine learning models and analyze large datasets to drive business decisions.",
    skills: ["Python", "Machine Learning", "SQL", "Data Visualization"],
    postedAt: "2023-06-10",
  },
  {
    id: "3",
    title: "UX/UI Designer",
    company: "DesignHub",
    companyLogo: "/image/logo3.jpg?height=100&width=100",
    location: "San Francisco, CA",
    type: "Contract",
    salary: "70/hr",
    description:
      "We're seeking a talented UX/UI Designer to create beautiful, intuitive interfaces for our clients' web and mobile applications.",
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping"],
    postedAt: "2023-06-05",
  },
  {
    id: "4",
    title: "Digital Marketing Specialist",
    company: "MarketMakers",
    companyLogo: "/image/logo4.jpg?height=100&width=100",
    location: "Remote",
    type: "Part-time",
    salary: "50K - 70K",
    description:
      "Help us grow our online presence through SEO, content marketing, and social media strategies.",
    skills: ["SEO", "Content Marketing", "Social Media", "Google Analytics"],
    postedAt: "2023-06-01",
  },
  {
    id: "5",
    title: "Mobile App Developer",
    company: "AppSolutions",
    companyLogo: "/image/logo5.jpg?height=100&width=100",
    location: "Austin, TX",
    type: "Full-time",
    salary: "80K - 110K",
    description:
      "Join our mobile development team to create innovative applications for iOS and Android platforms.",
    skills: ["React Native", "Swift", "Java", "Firebase"],
    postedAt: "2023-05-28",
  },
  {
    id: "6",
    title: "Content Writer",
    company: "ContentCreators",
    companyLogo: "/image/logo6.jpg?height=100&width=100",
    location: "Remote",
    type: "Freelance",
    salary: "30/hr",
    description:
      "We're looking for a creative content writer to produce engaging articles, blog posts, and marketing copy.",
    skills: ["Content Writing", "SEO", "Research", "Editing"],
    postedAt: "2023-05-25",
  },
  {
    id: "7",
    title: "Cybersecurity Analyst",
    company: "SecureTech",
    companyLogo: "/image/logo6.jpg?height=100&width=100",
    location: "Chicago, IL",
    type: "Full-time",
    salary: "90K - 120K",
    description:
      "Protect our company's information systems by monitoring for security breaches and responding to incidents.",
    skills: ["Network Security", "Penetration Testing", "Incident Response"],
    postedAt: "2023-05-20",
  },
  {
    id: "8",
    title: "Cloud Engineer",
    company: "CloudSolutions",
    companyLogo: "/image/logo6.jpg?height=100&width=100",
    location: "Remote",
    type: "Contract",
    salary: "100K - 130K",
    description:
      "Design and implement cloud-based solutions using AWS, Azure, or Google Cloud.",
    skills: ["AWS", "Azure", "Google Cloud", "DevOps"],
    postedAt: "2023-05-15",
  },
  {
    id: "9",
    title: "Game Developer",
    company: "GameStudio",
    companyLogo: "/image/logo6.jpg?height=100&width=100",
    location: "Los Angeles, CA",
    type: "Full-time",
    salary: "80K - 110K",
    description:
      "Join our game development team to create immersive gaming experiences using Unity or Unreal Engine.",
    skills: ["Unity", "C#", "Game Design", "3D Modeling"],
    postedAt: "2023-05-10",
  },
  {
    id: "10",
    title: "System Administrator",
    company: "TechOps",
    companyLogo: "/image/logo6.jpg?height=100&width=100",
    location: "Remote",
    type: "Part-time",
    salary: "60K - 80K",
    description:
      "Manage and maintain our IT infrastructure, ensuring system reliability and security.",
    skills: ["Linux", "Windows Server", "Networking", "Troubleshooting"],
    postedAt: "2023-05-05",
  },
];
export const allCourses: Course[] = [
  {
    id: "1",
    title: "Graphic Design",
    description:
      "Learn Graphic Design from scratch with this comprehensive course",
    instructor: "Alex william",
    thumbnail: "/image/graphic-design.jpg",
    rating: 4.8,
    reviewCount: 45892,
    students: "150K+",
    duration: "63h",
    level: "Intermediate",
    price: 3000,
    categories: ["Graphic Design", "Design", "Photoshop", "Illustrator"],
    whatYouWillLearn: [
      "Understand React fundamentals",
      "Build dynamic UI components",
      "Manage state with hooks",
      "Use React Router for navigation",
      "Integrate APIs into React apps",
    ],
    instructorPhoto: "/image/abra.jpg",
  },
  {
    id: "2",
    title: "Web Development",
    description:
      "Learn Web Development from scratch with this comprehensive course",
    instructor: "mark john",
    thumbnail: "/image/web-development.jpg",
    rating: 4.6,
    reviewCount: 32145,
    students: "120K+",
    duration: "44h",
    level: "Intermediate",
    price: 3000,
    categories: ["Web Development", "HTML", "CSS", "JavaScript"],
    whatYouWillLearn: [
      "Understand React fundamentals",
      "Build dynamic UI components",
      "Manage state with hooks",
      "Use React Router for navigation",
      "Integrate APIs into React apps",
    ],
    instructorPhoto: "/image/abra.jpg",
  },
  {
    id: "3",
    title: "Software Development",
    description:
      "Learn Software Development from scratch with this comprehensive course",
    instructor: "Abram boss",
    thumbnail: "/image/software-development.jpg",
    rating: 4.5,
    reviewCount: 23456,
    students: "90K+",
    duration: "52h",
    level: "Beginner",
    price: 3000,
    categories: ["Software Development", "Python", "Java", "C++"],
    whatYouWillLearn: [
      "Understand React fundamentals",
      "Build dynamic UI components",
      "Manage state with hooks",
      "Use React Router for navigation",
      "Integrate APIs into React apps",
      "Full admin dashboard with stats and montly sales chart as well as product, order and user management",
      "Full admin dashboard with stats and montly sales chart as well as product, order and user management",
      "Full admin dashboard with stats and montly sales chart as well as product, order and user management",
    ],
    instructorPhoto: "/image/abra.jpg",
  },
  {
    id: "4",
    title: "Digital Marketing",
    description:
      "Learn Digital Marketing from scratch with this comprehensive course",
    instructor: "Jane Doe",
    thumbnail: "/image/digital-marketing.jpg",
    rating: 4.7,
    reviewCount: 12345,
    students: "70K+",
    duration: "21h",
    level: "Advanced",
    price: 3000,
    categories: ["Digital Marketing", "SEO", "SEM", "Social Media Marketing"],
    whatYouWillLearn: [
      "Understand React fundamentals",
      "Build dynamic UI components",
      "Manage state with hooks",
      "Use React Router for navigation",
      "Integrate APIs into React apps",
    ],
    instructorPhoto: "/image/abra.jpg",
  },
  {
    id: "5",
    title: "Content Creation",
    description:
      "Learn Content Creation from scratch with this comprehensive course",
    instructor: "Jane Doe",
    thumbnail: "/image/content-creation.jpg",
    rating: 4.8,
    reviewCount: 45892,
    students: "150K+",
    duration: "63h",
    level: "Intermediate",
    price: 3000,
    categories: [
      "Content Creation",
      "Social Media Marketing",
      "Copywriting",
      "SEO",
    ],
    whatYouWillLearn: [
      "Understand React fundamentals",
      "Build dynamic UI components",
      "Manage state with hooks",
      "Use React Router for navigation",
      "Integrate APIs into React apps",
    ],
    instructorPhoto: "/image/abra.jpg",
  },
  {
    id: "6",
    title: "Mobile App Development",
    description:
      "Learn Mobile App Development from scratch with this comprehensive course",
    instructor: "John Doe",
    thumbnail: "/image/mobile-app-development.jpg",
    rating: 4.8,
    reviewCount: 45892,
    students: "150K+",
    duration: "63h",
    level: "Intermediate",
    price: 3000,
    categories: ["Mobile App Development", "Android", "iOS", "React Native"],
    whatYouWillLearn: [
      "Understand React fundamentals",
      "Build dynamic UI components",
      "Manage state with hooks",
      "Use React Router for navigation",
      "Integrate APIs into React apps",
    ],
    instructorPhoto: "/image/abra.jpg",
  },
  {
    id: "7",
    title: "Artificial Intelligence",
    description:
      "Learn Artificial Intelligence from scratch with this comprehensive course",
    instructor: "John Doe",
    thumbnail: "/image/artificial-intelligence.jpg",
    rating: 4.8,
    reviewCount: 45892,
    students: "150K+",
    duration: "63h",
    level: "Intermediate",
    price: 3000,
    categories: [
      "Artificial Intelligence",
      "Machine Learning",
      "Deep Learning",
      "Natural Language Processing",
    ],
    whatYouWillLearn: [
      "Understand React fundamentals",
      "Build dynamic UI components",
      "Manage state with hooks",
      "Use React Router for navigation",
      "Integrate APIs into React apps",
    ],
    instructorPhoto: "/image/abra.jpg",
  },
  {
    id: "8",
    title: "UI/UX Design",
    description:
      "Learn UI/UX Design from scratch with this comprehensive course",
    instructor: "John Doe",
    thumbnail: "/image/ui-ux.jpg",
    rating: 4.8,
    reviewCount: 45892,
    students: "150K+",
    duration: "63h",
    level: "Intermediate",
    price: 3000,
    categories: ["UI/UX Design", "Figma", "Adobe XD", "Sketch"],
    whatYouWillLearn: [
      "Understand React fundamentals",
      "Build dynamic UI components",
      "Manage state with hooks",
      "Use React Router for navigation",
      "Integrate APIs into React apps",
    ],
    instructorPhoto: "/image/abra.jpg",
  },
  {
    id: "9",
    title: "Amharic Language",
    description:
      "Learn Amharic Language from scratch with this comprehensive course",
    instructor: "John Doe",
    thumbnail: "/image/Amharic.jpg",
    rating: 4.8,
    reviewCount: 45892,
    students: "150K+",
    duration: "63h",
    level: "Intermediate",
    price: 3000,
    categories: [
      "Amharic Language",
      "Amharic Grammar",
      "Amharic Vocabulary",
      "Amharic Pronunciation",
    ],
    whatYouWillLearn: [
      "Understand React fundamentals",
      "Build dynamic UI components",
      "Manage state with hooks",
      "Use React Router for navigation",
      "Integrate APIs into React apps",
    ],
    instructorPhoto: "/image/abra.jpg",
  },
  {
    id: "10",
    title: "Somali Language",
    description:
      "Learn Somali Language from scratch with this comprehensive course",
    instructor: "John Doe",
    thumbnail: "/image/somali.jpg",
    rating: 4.8,
    reviewCount: 45892,
    students: "150K+",
    duration: "63h",
    level: "Intermediate",
    price: 3000,
    categories: [
      "Somali Language",
      "Somali Grammar",
      "Somali Vocabulary",
      "Somali Pronunciation",
    ],
    whatYouWillLearn: [
      "Understand React fundamentals",
      "Build dynamic UI components",
      "Manage state with hooks",
      "Use React Router for navigation",
      "Integrate APIs into React apps",
    ],
    instructorPhoto: "/image/abra.jpg",
  },
  {
    id: "11",
    title: "Oromic Language",
    description:
      "Learn Oromic Language from scratch with this comprehensive course",
    instructor: "John Doe",
    thumbnail: "/image/oromic.jpg",
    rating: 4.8,
    reviewCount: 45892,
    students: "150K+",
    duration: "63h",
    level: "Intermediate",
    price: 3000,
    categories: [
      "Oromo Language",
      "Oromo Grammar",
      "Oromo Vocabulary",
      "Oromo Pronunciation",
    ],
    whatYouWillLearn: [
      "Understand React fundamentals",
      "Build dynamic UI components",
      "Manage state with hooks",
      "Use React Router for navigation",
      "Integrate APIs into React apps",
    ],
    instructorPhoto: "/image/abra.jpg",
  },
];
